### ISSUE TITLE
[shadow] Annoying conversion of long_file_name to long<em>file</em>name (intra-word emphasis)

### ISSUE THREAD

**Issue by trentm** [trentm/python-markdown2#38] opened 2011-03-07 05:09 UTC
_This is a *_shadow issue*\* for [Issue 38 on Google Code](http://code.google.com/p/python-markdown2/issues/detail?id=38) (from which this project was moved).
Added 2010-05-28T02:53:47.000Z by [samtaufa](http://code.google.com/u/samtaufa/).
Labels: Type-Enhancement, Priority-Medium.
Please make updates to the bug [there](http://code.google.com/p/python-markdown2/issues/detail?id=38).*
# Original description

```
Started using markdown2 and one of my faults with the conversion is that we
use a lot of long_file_names_with_underscores.

Unfortunately, this causes the generated pages to look real wacky with
italics happening in unexpected places, and variables  and filenames not
being correct.

The change was to wrap the re.compile sequences in markdown2.py with &quot;\b&quot;
as per the below example.
Index: lib/markdown2.py
===================================================================
--- lib/markdown2.py    (revision 248)
+++ lib/markdown2.py    (working copy)
@@ -1408,10 +1408,10 @@
             text = text.replace(before, after)
         return text

-    _strong_re = re.compile(r&quot;(\*\*|__)(?=\S)(.+?[*_]*)(?<=\S)\1&quot;, re.S)
-    _em_re = re.compile(r&quot;(\*|_)(?=\S)(.+?)(?<=\S)\1&quot;, re.S)
-    _code_friendly_strong_re =
re.compile(r&quot;\*\*(?=\S)(.+?[*_]*)(?<=\S)\*\*&quot;, re.S)
-    _code_friendly_em_re = re.compile(r&quot;\*(?=\S)(.+?)(?<=\S)\*&quot;, re.S)
+    _strong_re = re.compile(r&quot;\b(\*\*|__)(?=\S)(.+?[*_]*)(?<=\S)\1\b&quot;, re.S)
+    _em_re = re.compile(r&quot;\b(\*|_)(?=\S)(.+?)(?<=\S)\1\b&quot;, re.S)
+    _code_friendly_strong_re =
re.compile(r&quot;\b\*\*(?=\S)(.+?[*_]*)(?<=\S)\*\*\b&quot;, re.S)
+    _code_friendly_em_re = re.compile(r&quot;\b\*(?=\S)(.+?)(?<=\S)\*\b&quot;, re.S)
     def _do_italics_and_bold(self, text):
         # <strong> must go first:
         if &quot;code-friendly&quot; in self.extras:
I'm not sure if this is an acceptable change, since the 'standard' seems to
be ambiguous(?) about the expected behaviour ?


Hope this helps,


Sam T.
```

**Comment by zx2c4** [comment] 2016-02-23 05:16
Any update on this?

**Comment by nicholasserra** [comment] 2016-02-23 05:18
@zx2c4 Using the code-friendly extra will disable this https://github.com/trentm/python-markdown2/wiki/code-friendly

**Comment by fviolette** [comment] 2019-05-24 08:29
Hello — any foreseeable improvement on `disabling **just** intra-word emphasis`?
This would solve a fair share of GFM-md facepalms from my experience.

**Comment by codebykat** [comment] 2020-12-03 04:26
+1 for some more nuanced options here. I'm currently doing a second pass that finds any `<em>` opening or closing tags within URLs and changes them back to underscores. We didn't want to disable the underscore syntax entirely, and even all intra-word emphasis would probably be overkill, but as it stands it mangles URLs (which is to say URLs which are not Markdown links, just URLs in the text).

**Comment by rouilj** [comment] 2023-07-20 19:36
Have there been any further thoughts/work on this?

My use case is to render a markdown document created in the browser with a javascript markdown previewer.
Because of this bug, the two don't have parity leading to user confusion.

The issue is the intra_word emphasis.

The ticket on my side is: https://issues.roundup-tracker.org/issue2551105
 
From the original message:
```
When writing markdow like: 'self.this_long_attr'

markdown2 replaces the '_' by <em>
markdown does not replace
mistune does not replace
simplemde does not replace
```

Thanks.

**Comment by Crozzers** [comment] 2023-07-23 13:48
Hi all, I've created a linked PR to address this. Let me know if there's anything I missed or that needs changing

**Closed** 2023-07-23 17:16 UTC
