### ISSUE TITLE
2.3.2 regression: fully-qualified links are urlencoded

### ISSUE THREAD

**Issue by lopopolo** [trentm/python-markdown2#233] opened 2016-12-06 04:09 UTC
I think this is caused by GH-230.

Sample markdown code:

```markdown
[GitHub](https://github.com/lopopolo)
```

Under 2.3.1 with safe_mode = escape renders the following link:

```html
<a href="https://github.com/lopopolo">GitHub</a>
```

Under 2.3.2 with safe_mode = escape renders the following link:

```html
<a href="https%3A%2F%2Fgithub.com%2Flopopolo">GitHub</a>
```

**Comment by nicholasserra** [comment] 2016-12-06 05:56
Thanks for the report. Not sure how tests didn't catch this.

**Comment by lopopolo** [comment] 2016-12-07 03:25
Because the tests enforce this behavior:

https://github.com/trentm/python-markdown2/pull/230/files#diff-2975f6a2bb599e9479d075d841dbdbccR11

There are also no safe mode happy path tests (i.e.: ensuring a valid link with nothing needing to be escaped turns into a valid link)

**Comment by nicholasserra** [comment] 2016-12-19 16:15
Fixed in #236

**Closed by nicholasserra** 2016-12-19 16:15 UTC

**Comment by stefanw** [comment] 2017-01-24 12:28
Thanks for the fix! Because of the regression, please consider releasing 2.3.3.

**Comment by nicholasserra** [comment] 2017-02-04 01:19
2.3.3 released
