### ISSUE TITLE
Interference between code blocks and latex

### ISSUE THREAD

**Issue by franciszekjuras** [trentm/python-markdown2#411] opened 2022-01-27 12:42 UTC
If latex command begins with a letter, which is later enclosed in code block, backslashes before command disappear.
Compare:
"""python
>>> import markdown2
>>> markdown2.markdown('$n \\leq 0$.\n`l` is interfering.')
'<p>$n leq 0$.\n<code>l</code> is interfering.</p>\n'
>>> markdown2.markdown('$n \\leq 0$.\n`xl` is interfering.')
'<p>$n \\leq 0$.\n<code>xl</code> is interfering.</p>\n'
"""

**Comment by Crozzers** [comment] 2023-03-11 19:41
@nicholasserra I think this issue was a duplicate of #412 which was fixed with PR #421. This issue can probably be closed

**Closed** 2023-03-13 02:27 UTC
