### ISSUE TITLE
UTF-8 Byte order mark is not recognised

### ISSUE THREAD

**Issue by RolfBly** [trentm/python-markdown2#177] opened 2015-02-18 19:44 UTC
If the markdown source is UTF-with byte order mark, markdown2.py will crash with the message below. The workaround is easy, just save the file again as UTF-8 without BOM.  However one does have to remember that for every file. 

```
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 171, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python34\lib\site-packages\markdown2.py", line 2458, in <module>
    sys.exit( main(sys.argv) )
  File "C:\Python34\lib\site-packages\markdown2.py", line 2437, in main
    sys.stdout.write(html)
  File "C:\Python34\lib\encodings\cp850.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 3: character maps to <undefined>
```

**Comment by jose1711** [comment] 2024-07-11 14:40
tested with current release - there is no crash but BOM makes its way into HTML which is of course undesirable.

**Comment by Crozzers** [comment] 2024-07-17 16:19
How is the library being invoked?

On the CLI, there's a `--encoding` option to manually specify the encoding, in the `markdown_path` function there's an `encoding` kwarg that does the same thing. Would that solve the issue?

**Comment by jose1711** [comment] 2024-07-18 19:05
`--encoding` does not seem to have a positive effect.

```sh
$ python -m venv markdown2

$ source markdown2/bin/activate.fish

$ pip install markdown2

$ echo '
import codecs
with codecs.open("test.md", "w", "utf-8-sig") as f:
     f.write("# foo\n")
     f.write("# bar\n")
' | python -

$ file test.md
test.md: Unicode text, UTF-8 (with BOM) text

$ cat test.md
# foo
# bar

$ cat -vte test.md
M-oM-;M-?# foo$
# bar$

$ markdown2 test.md | cat
<p>﻿# foo</p>

<h1>bar</h1>


$ markdown2 test.md | cat -vte
<p>M-oM-;M-?# foo</p>$
$
<h1>bar</h1>$

# test with --encoding:
markdown2 --encoding utf8 test.md | cat -vte
<p>M-oM-;M-?# foo</p>$
$
<h1>bar</h1>$
```

**Comment by Crozzers** [comment] 2024-07-20 10:10
The file was written with `utf-8-sig` but in the example you're passing `utf8` to the `--encoding` parameter. Does it change the result if you pass `--encoding utf-8-sig`?

**Comment by Crozzers** [comment] 2024-07-23 20:44
To do that we'd have to guess the encoding of the file. There is a PyPI package that does that called [Chardet](https://pypi.org/project/chardet/) which you might be able to use in your case, but I think it's unlikely to be added as an optional dependency in this library as I don't think that's the responsibility of this library to handle

**Comment by nicholasserra** [comment] 2024-07-24 00:21
Agreed

**Comment by jose1711** [comment] 2024-07-24 07:07
Thank you for your response. I think you always assume using `python-markdown2` as a library - i. e. by a developer who knows what an encoding is etc. But think of a Windows user, who read somewhere on the internet how to install Python and pull a package from a PIP. Often he does not even have a clue what a BOM is, or chardet etc.

Perhaps at least a word of warning could be shown when the first characters ready by the library are 0xEF, 0xBB, 0xBF.

**Comment by Crozzers** [comment] 2024-07-27 16:17
My first thought about this is: if we go to the effort of detecting a particular BOM and emitting a warning, why not just decode it correctly?

And in the case of the Windows user, it looks like MS has been working on [wider UTF-8 support since 2017](https://en.wikipedia.org/wiki/Unicode_in_Microsoft_Windows#UTF-8). UTF-8 (without BOM) has been the default encoding for notepad [since Windows 10 version 1903](https://www.bleepingcomputer.com/news/microsoft/windows-10-notepad-is-getting-better-utf-8-encoding-support/) (released May 2019).

Looking at another parser for reference, [Markdown](https://github.com/Python-Markdown/markdown) hasn't done BOM detection since [this commit in 2008](https://github.com/Python-Markdown/markdown/commit/40b8986ccf0ea3fa37dda469b46261dfbf0c25a4). Nowadays, it looks like they only strip out the [UTF-16 (BE) BOM](https://github.com/Python-Markdown/markdown/blob/33359faa385f59b84cd87df5f4b0996055a482e2/markdown/core.py#L428) but not any others (I don't know why).

Overall, I don't think this problem is within the scope of this project, especially given Microsoft's UTF-8 push over the past few years.

**Comment by jose1711** [comment] 2024-07-29 08:24
> Overall, I don't think this problem is within the scope of this project, especially given Microsoft's UTF-8 push over the past few years.

Thank you for your time spent on the analysis. I believe you made a fair point, plus the problem is not bothering me that much. Also, I'd like to express my gratitude for contributing to this project. Closing.

**Closed** 2024-07-29 18:21 UTC
